### ISSUE TITLE
Theos install failed 

### ISSUE THREAD

**Issue by Envisiond** [Randy-420/Theos-Auto-Installer-u0-Checkra1n-odyssey#1]
iPhone XS Max 
iOS 13.5
Unc0ver 13.5

Trying to install Theos but when I run “tai” I get the following.

“ iPhone:~ mobile$ tai
                Theos Auto Installer by Randy420

/bin/sh: line 1: 10734 Done                    echo "mkdir /var/mobile/tweaks"
     10735 Segmentation fault: 11  | GaPp
/bin/sh: line 1: 10738 Done                    echo "git clone --recursive https://github.com/theos/theos.git /var/theos"
     10739 Segmentation fault: 11  | GaPp

[Failed to make /var/mobile/tweaks]

[Theos install FAILED!]

iPhone:~ mobile$ “
 
 Running as su and have got my udid but not sure where to put that since I don’t see anywhere in the setting to enter my key or if it’s even needed anymore. The other commands basically say the same thing

**Comment by MNS82** [comment]
Same here

**Comment by Randy-420** [comment]
Is that still happening?

You need to run it as root:

Either run:
gap
tai

Or:
su
alpine
tai
